//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Order = new HashSet<Order>();
        }
        [DisplayName("車牌")]
        public string carID { get; set; }
        [DisplayName("車款描述")]
        public string description { get; set; }
        [DisplayName("廠牌編號")]
        public string brandID { get; set; }
        [DisplayName("車型編號")]
        public int typeID { get; set; }
        [DisplayName("座位數量")]
        public decimal seatNume { get; set; }
        [DisplayName("排檔")]
        public string transmission { get; set; }
        [DisplayName("行李描述")]
        public string luggages { get; set; }
        [DisplayName("其他")]
        public string others { get; set; }
        [DisplayName("照片")]
        public string Photo { get; set; }
        [DisplayName("淡季租金")]
        public decimal rent1 { get; set; }
        [DisplayName("旺季租金")]
        public Nullable<decimal> rent2 { get; set; }
        [DisplayName("出廠日期")]
        public System.DateTime carDate { get; set; }
        [DisplayName("建檔日期")]
        public System.DateTime bDate { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual carType carType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
