//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Order = new HashSet<Order>();
        }
        [DisplayName("會員編號")]
        public int memberID { get; set; }
        [DisplayName("會員姓名")]
        public string name { get; set; }
        [DisplayName("密碼")]
        public string Passwd { get; set; }
        [DisplayName("身分證/或護照號碼")]
        public string ID { get; set; }
        [DisplayName("性別")]
        public string Gender { get; set; }
        [DisplayName("生日")]
        public System.DateTime Birthday { get; set; }
        [DisplayName("駕照存放路徑")]
        public string licenses { get; set; }
        [DisplayName("連絡電話")]
        public string Phone { get; set; }
        [DisplayName("Email")]
        public string Email { get; set; }
        [DisplayName("緊急聯絡人")]
        public string emgyContact { get; set; }
        [DisplayName("緊急聯絡人關係")]
        public string relationship { get; set; }
        [DisplayName("緊急連絡人電話")]
        public string emgyPhone { get; set; }
        [DisplayName("註冊日期")]
        public System.DateTime bDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
