//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Order
    {
        [DisplayName("訂單編號")]
        public string orderID { get; set; }
        [DisplayName("會員編號")]
        public int memberID { get; set; }
        [DisplayName("取車編號")]
        public string rentID { get; set; }
        [DisplayName("還車編號")]
        public string returnID { get; set; }
        [DisplayName("取車日期")]
        public System.DateTime orderDate { get; set; }
        [DisplayName("還車日期")]
        public System.DateTime returnDate { get; set; }
        [DisplayName("車牌編號")]
        public string carID { get; set; }
        [DisplayName("郵件發送狀態")]
        public bool emailSent { get; set; }
        [DisplayName("付款狀態")]
        public bool payStat { get; set; }
        [DisplayName("租金總額")]
        public Nullable<int> rentC { get; set; }
        [DisplayName("是否還車")]
        public bool rentReturn { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Member Member { get; set; }
        public virtual RentLocation RentLocation { get; set; }
        public virtual ReturnLocation ReturnLocation { get; set; }
    }
}
